name: mydeardiary
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
   sdk: flutter
  graphql_flutter: 5.0.1
  dio: 4.0.0
  flutter_colorpicker: ^1.0.3
  http:
  equatable:
  injector: 2.0.0
  intl: 0.17.0
  get: 4.3.8
  shimmer: ^2.0.0
  shared_preferences: 2.0.8
  cupertino_icons: 1.0.3
  mask_text_input_formatter: 2.0.0
  flutter_lints: ^1.0.0
  # cloud_firestore: ^0.12.9+5
  # firebase_auth: ^0.14.0+5
  # firebase_core: ^0.4.0+9
  local_auth: 1.1.11
  page_turn:
    git:
      url: https://github.com/LucasMasayuki/page_turn

dev_dependencies:
  build_runner:
  faker: 2.0.0
  mockito: 5.0.16
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
  - family: Festive
    fonts:
      - asset: assets/fonts/Festive-Regular.ttf
  - family: AreYouSerious
    fonts:
      - asset: assets/fonts/AreYouSerious-Regular.ttf
  - family: Birthstone
    fonts:
      - asset: assets/fonts/Birthstone-Regular.ttf
  - family: Ephesis
    fonts:
      - asset: assets/fonts/Ephesis-Regular.ttf
  - family: IndieFlower
    fonts:
      - asset: assets/fonts/IndieFlower-Regular.ttf