name: mydeardiary
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
   sdk: flutter
  graphql_flutter: 5.0.0
  dio: 4.0.0
  http:
  equatable:
  injector: 2.0.0
  intl: 0.17.0
  get: 4.3.8
  shimmer: ^2.0.0
  shared_preferences: 2.0.8
  cupertino_icons: 1.0.3
  mask_text_input_formatter: 2.0.0
  page_turn:
    git:
      url: https://github.com/LucasMasayuki/page_turn

dev_dependencies:
  build_runner:
  faker: 2.0.0
  mockito: 5.0.16
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
  - family: Festive
    fonts:
      - asset: assets/fonts/Festive-Regular.ttf
  - family: AreYouSerious
    fonts:
      - asset: assets/fonts/AreYouSerious-Regular.ttf
  - family: Birthstone
    fonts:
      - asset: assets/fonts/Birthstone-Regular.ttf
  - family: Ephesis
    fonts:
      - asset: assets/fonts/Ephesis-Regular.ttf
  - family: IndieFlower
    fonts:
      - asset: assets/fonts/IndieFlower-Regular.ttf